apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kflask
  namespace: default
spec:
  interval: 5m
  url: https://github.com/stefanprodan/kflask
  ref:
    branch: master
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kflask
  namespace: default
spec:
  interval: 10m
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: kflask
  path: "./manifests"
  prune: true
  timeout: 1m