
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- deployment.yaml
metadata:
  name: flask-app
  namespace: flux-system
spec:
  interval: 5m
  path: "./manifests"
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: default  # ← Deploys resources to this ns